name: Build
on:
  push:
    tags:
      - v*
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Setup required gcc
        run: sudo apt install gcc-13 g++-13

      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: Ninja
          c-compiler: gcc-13
          cxx-compiler: g++-13

      - name: Build the project
        run: cmake --build build

      - name: Create Archive
        run: |
          cp bin parsumo
          zip -r parsumo.zip parsumo
        working-directory: ${{ github.workspace }}
