name: Build-Ubuntu
on:
  push:
    tags:
      - v*
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: |
          sudo add-apt-repository ppa:sumo/stable
          sudo apt update
          sudo apt install gcc-13 g++-13 sumo sumo-tools sumo-doc libzmq3-dev ninja-build nlohmann-json3-dev libboost-all-dev cmake libc++-dev

      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: Ninja
          c-compiler: gcc-13
          cxx-compiler: g++-13
        env:
          SUMO_HOME: /usr/share/sumo

      - name: Build the project
        run: cmake --build build
        env:
          SUMO_HOME: /usr/share/sumo

      - name: Create Archive
        run: |
          cp bin parsumo
          zip -r parsumo_x86_64-linux-gnu.zip parsumo
        working-directory: ${{ github.workspace }}

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: parsumo_x86_64-linux-gnu
          path: parsumo_x86_64-linux-gnu.zip
  