name: build
on:
  push:
    tags:
      - 'v[0-9].*'

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: 'echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT'

      - name: Install requirements
        run: |
          sudo add-apt-repository ppa:sumo/stable
          sudo apt update
          sudo apt install gcc-13 g++-13 sumo sumo-tools sumo-doc libzmq3-dev ninja-build nlohmann-json3-dev libboost-all-dev cmake libc++-dev

      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Configure the project
        run: ./configure.sh
        env:
          SUMO_HOME: /usr/share/sumo

      - name: Build the project
        run: cmake --build build
        env:
          SUMO_HOME: /usr/share/sumo

      - name: Create distribution
        id: dist
        run: "scripts/dist.sh \"linux-gnu_${{ steps.get_version.outputs.VERSION }}\" | grep -oE 'Saved to: .*$' | cut -d ' ' -f 3 | sed 's/.*/DIST=&/' >> $GITHUB_OUTPUT"
        working-directory: ${{ github.workspace }}

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.dist.outputs.DIST }}
          path: ${{ steps.dist.outputs.DIST }}
  